version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"